### ISSUE TITLE
试一下 Slides

### ISSUE THREAD

**Issue by impasse** [lingmm/IssueBlog#14]
<iframe src="https://docs.google.com/presentation/d/1O8c_O9bvtiKxPbAfABEoDl7t37cUWj76dHUyvvauCq0/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

**Comment by starlightme** [comment]
这个是啥。。页面放类似PPT的东西嘛~

**Comment by starlightme** [comment]
厉害了。。居然在GitHub的ISSUE里面。。黑科技

**Comment by ysicing** [comment]
厉害了我的哥

**Comment by impasse** [comment]
>@starlightme: 这个是啥。。页面放类似PPT的东西嘛~

差不多吧

**Comment by impasse** [comment]
>@ysicing: 厉害了我的哥

哈
